#!/usr/bin/env bash
#
# Dépendance de cette bibliothèque : 
# - commun

#####
## VARIABLES
###

# Nom du fichier Docker Compose final (pour l'instance)
NOM_FICHIER_DOCKER_COMPOSE="${NOM_FICHIER_DOCKER_COMPOSE:-docker-compose.yml}"
# Adresse de l'entête utilisée pour le fichier Docker Compose final
ENTETE_DOCKER_COMPOSE="./modeles/entete.yml"

#####
## FONCTIONS
###

# Création du fichier docker-compose.yml dans le dossier donné
# 1: Répertoire dans lequel créer le fichier docker-compose.yml
creer_fichier_docker_compose() {

  repertoire="${1}"

  # contrôle du répertoire
  if [[ -z "${repertoire}" ]]; then
    msg_erreur_exit "Aucun répertoire donné"
  elif [[ ! -d "${repertoire}" ]]; then
    msg_erreur_exit "Répertoire non trouvé : ${repertoire}"
  fi

  docker_compose="${repertoire}/${NOM_FICHIER_DOCKER_COMPOSE}"

  # entête du fichier final
  cat "${ENTETE_DOCKER_COMPOSE}" > "${docker_compose}"

  # ajout de chacun des services
  for service in ${LISTE_SERVICES[@]}; do
    fichier_service="${REP_SERVICES}/${service}/${NOM_FICHIER_SERVICE}"

    # contrôle existance du fichier de description du service
    if [[ ! -f "${fichier_service}" ]]; then
      msg_erreur_exit "Le fichier ${fichier_service} n'existe pas !"
    fi

    # concaténation du contenu avec le fichier final
    cat "${fichier_service}"|sed -e 's#^#  #g' >> "${docker_compose}"
  done

  msg_succes "Fichier Docker Compose: ${docker_compose}"
}

# Suppression des conteneurs liés au dossier donné (contenant un fichier
# docker-compose.yml)
# 1: Répertoire dans lequel se trouve le fichier docker-compose.yml
suppression_conteneurs() {

  repertoire="${1}"
  docker_compose="${repertoire}/${NOM_FICHIER_DOCKER_COMPOSE}"

  # Vérification contenu du répertoire
  if [[ ! -f "${docker_compose}" ]]; then
    msg_erreur_exit "Fichier Docker Compose non trouvé dans : ${repertoire}"
  fi

  # Arrêt des conteneurs Docker
  docker compose -f "${docker_compose}" kill || msg_erreur_exit "Souci \
avec Docker"
  # Suppression des conteneurs
  docker compose -f "${docker_compose}" down || msg_erreur_exit "Souci \
avec Docker"

  msg_succes "Arrêt des conteneurs Docker"
}

# vim: ts=2 sw=2 et nu syn=bash
