#!/usr/bin/env bash
#
# Dépendance de cette bibliothèque : 
# - commun

#####
## VARIABLES
###

# Nom du fichier Docker Compose final (pour l'instance)
NOM_FICHIER_DOCKER_COMPOSE="${NOM_FICHIER_DOCKER_COMPOSE:-docker-compose.yml}"
# Adresse de l'entête utilisée pour le fichier Docker Compose final
ENTETE_DOCKER_COMPOSE="./modeles/entete.yml"
# Message d'erreur commun aux problèmes Docker
MSG_ERR_DOCKER="Souci avec Docker"

#####
## FONCTIONS
###

# Création du fichier docker-compose.yml dans le dossier donné
# 1: Répertoire dans lequel créer le fichier docker-compose.yml
creer_fichier_docker_compose() {

  repertoire="${1}"

  # contrôle du répertoire
  if [[ -z "${repertoire}" ]]; then
    msg_erreur_exit "Aucun répertoire donné"
  elif [[ ! -d "${repertoire}" ]]; then
    msg_erreur_exit "Répertoire non trouvé : ${repertoire}"
  fi

  docker_compose="${repertoire}/${NOM_FICHIER_DOCKER_COMPOSE}"

  # entête du fichier final
  cat "${ENTETE_DOCKER_COMPOSE}" > "${docker_compose}"

  # ajout de chacun des services
  for service in ${LISTE_SERVICES[@]}; do
    fichier_service="${REP_SERVICES}/${service}/${NOM_FICHIER_SERVICE}"

    # contrôle existance du fichier de description du service
    if [[ ! -f "${fichier_service}" ]]; then
      msg_erreur_exit "Le fichier ${fichier_service} n'existe pas !"
    fi

    # concaténation du contenu avec le fichier final
    cat "${fichier_service}"|sed -e 's#^#  #g' >> "${docker_compose}"
  done

  msg_succes "Fichier Docker Compose: ${docker_compose}"
}

# Test si le fichier Docker Compose existe, sinon retourne une erreur
# 1: Fichier Docker Compose
test_existence_fichier_compose() {
  fichier="${1}"

  if [[ -z "${fichier}" ]]; then
    msg_erreur_exit "Aucun fichier Docker Compose fourni."
  fi

  # Si le fichier n'existe pas, on s'arrête !
  if [[ ! -f "${fichier}" ]]; then
    msg_erreur_exit "Fichier Docker Compose non trouvé : ${fichier}"
  fi
}

# Démarrage des conteneurs liés au dossier donné (contenant un fichier
# docker-compose.yml)
# 1: Répertoire dans lequel se trouve le fichier docker-compose.yml
demarre_conteneurs() {

  repertoire="${1}"
  docker_compose="${repertoire}/${NOM_FICHIER_DOCKER_COMPOSE}"

  # Vérification que le fichier Docker Compose existe
  test_existence_fichier_compose "${docker_compose}"

  # Démarrage des conteneurs
  msg_info "Démarrage des conteneurs Docker"
  docker-compose -f "${docker_compose}" up -d || msg_erreur_exit \
    "${MSG_ERR_DOCKER}"

  msg_succes "Conteneurs Docker lancés"
}

# Suppression des conteneurs liés au dossier donné (contenant un fichier
# docker-compose.yml)
# 1: Répertoire dans lequel se trouve le fichier docker-compose.yml
suppression_conteneurs() {

  repertoire="${1}"
  docker_compose="${repertoire}/${NOM_FICHIER_DOCKER_COMPOSE}"

  # Vérification que le fichier Docker Compose existe
  test_existence_fichier_compose "${docker_compose}"

  # Arrêt des conteneurs Docker
  docker compose -f "${docker_compose}" kill || msg_erreur_exit \
    "${MSG_ERR_DOCKER}"
  # Suppression des conteneurs
  docker compose -f "${docker_compose}" down || msg_erreur_exit \
    "${MSG_ERR_DOCKER}"

  msg_succes "Arrêt des conteneurs Docker"
}

# vim: ts=2 sw=2 et nu syn=bash
