#!/usr/bin/env bash
#
# Dépendance de cette bibliothèque : 
# - commun
# - docker

#####
## VARIABLES
###

# Profil par défaut pour créer des instances
PROFIL="${PROFIL:-defaut}"

# Répertoire dans lequel seront installées les instances
REP_INSTANCES="${REP_INSTANCES:-./instances}"
# Répertoire dans lequel trouver les profils
REP_PROFILS="${REP_PROFILS:-./profils}"

# Liste des services trouvés
LISTE_SERVICES=()

####
## FONCTIONS
###

# Découvre les services associés dans le fichier fourni
# Fonction récursive
# 1: Nom du profil situé dans le dossier ./profils
decouverte_services() {
  fichier="./profils/${1}"

  # Interruption si profil non trouvé.
  if [[ ! -f "./profils/${1}" ]]; then
    msg_erreur_exit "Profil '${1}' non trouvé !"
  fi

  # Chargement des données fournies dans le fichier
  source "${fichier}"

  # Enregistrement des services fournis si la variable existe
  if [[ -n "${SERVICES}" ]]; then
    # chargement du tableau
    les_services="${SERVICES[@]}"

    # Comme nous sommes dans une récursive, on interrompt le processus en
    # supprimant la variable SERVICES
    unset SERVICES

    # Enregistrement
    for service in "${les_services[@]}"; do
      LISTE_SERVICES+=( "${service}" )
    done

  fi

  # Les fichiers peuvent avoir un parent
  if [[ -n "${PARENT}" ]]; then
    # chargement du parent
    profil_parent="${PARENT}"
    unset PARENT

    # récupération des services du parent
    decouverte_services "${profil_parent}"
  fi
}

# Liste des profils disponibles comme base pour les instances
lister_profils() {
  detection=false

  for profil in `ls "${REP_PROFILS}"`; do
    # Exclusion du profil commun
    if [[ "${profil}" != "commun" ]]; then
      msg "${profil}"
      detection=true
    fi
  done

  if ! ${detection}; then
    msg_attention "Aucun profil trouvé."
  fi
}

# Listing des services trouvés
lister_services() {
  for service in ${LISTE_SERVICES[@]}; do
    msg_info "Service : ${service}"
  done
}


# Traite le chargement d'un profil
# 1: Nom du profil situé dans le dossier ./profils
charger_profil() {
  # Découverte de l'ensemble des services associés au fichier fourni
  decouverte_services "${1}"

  # Listing des services trouvés
  lister_services  
}

# Créé une instance à partir du profil donné en argument.
# 1: Nom du profil situé dans le dossier ./profils
creer_instance() {
  # Répertoire de l'instance
  instance="${REP_INSTANCES}/${1}"

  # Vérification de la présence du dossier
  if [[ ! -d "${instance}" ]]; then
    mkdir -p "${instance}" && msg_succes "Création répertoire '${instance}'"
  fi

  # TODO: si le dossier existait déjà, il faut couper les conteneurs

  # Création du fichier docker-compose.yml
  creer_fichier_docker_compose "${instance}"

  # Démarrage des conteneurs Docker
  demarre_conteneurs "${instance}"
}

# Listing des instances installées
lister_instances() {
  detection=false

  if [[ ! -d "${REP_INSTANCES}" ]]; then
    msg_erreur_exit "Répertoire d'instance manquant : ${REP_INSTANCES}"
  fi

  msg_info "Liste des instances"

  # Liste des dossiers du répertoire des instances
  for instance in `ls "${REP_INSTANCES}"`; do
    fichier="${REP_INSTANCES}/${instance}/${NOM_FICHIER_DOCKER_COMPOSE}"
    if [[ -f "${fichier}" ]]; then
      msg "  - ${REP_INSTANCES}/${instance}"
      detection=true
    fi
  done

  if ! ${detection}; then
    msg_attention "Aucune instance trouvée."
  fi
}

# Supprime l'instance donnée
# 1: Nom de l'instance
supprimer_instance() {
  nom_instance="${1}"
  instance="${REP_INSTANCES}/${nom_instance}"

  # Contrôle de l'existence de l'instance
  if [[ ! -d "${instance}" ]]; then
    msg_erreur_exit "Instance non trouvée : ${instance}"
  fi

  # Alerte à l'utilisateur pour éviter les erreurs
  msg_attention "Êtes-vous sûr de vouloir supprimer l'instance ${instance} ? (o/N)"
  read reponse

  case "${reponse}" in
    o|O)
      msg_info "Suppression de : ${instance}"

      # Extinction d'éventuels conteneurs lancés
      suppression_conteneurs "${instance}"

      # Suppression de l'instance
      rm -rf "${instance}"

      msg_succes "Instance supprimée : ${1}"
      ;;
    *)
      msg_info "Aucune instance supprimée."
      ;;
  esac
}

# vim: ts=2 sw=2 et nu syn=bash
