#!/usr/bin/env bash
#
# genese: Outil pour générer des instances d'un à plusieurs projets via
#   Docker Compose en utilisant des profils pour savoir quels services
#   utiliser.
#

PROGRAMME=`basename $0 .sh`

#####
## VARIABLES
###

# Dépôt d'origine à télécharger
SOURCE="git@github.com:blankoworld/genese.git"

# Message d'utilisation du programme
read -d '' UTILISATION << EOF
Utilisation : ${PROGRAMME} [options]

OPTIONS
  -l, --list                Liste des profils disponibles
  -h, --help                Affichage de l'aide contextuelle
  -p, --profil <profil>     Utilisation du profil

EXEMPLE

    ${PROGRAMME} -h

EOF

#####
## FONCTIONS
###

# Affiche l'aide contextuelle
aide() {
 echo -e "${UTILISATION}" 1>&2
}

#####
## ARGUMENTS
###

[ "$#" -lt 1 ] && aide && exit 1

#####
## TESTS
###

#####
## DÉBUT
###

# Chargement des bibliothèques
source "./bibliotheques/commun"
source "./bibliotheques/profils"

# Parcours des options
while [[ "$#" -gt 0 ]]
do
  case "$1" in
      -p | --profil)
      PROFIL="${2}"
      charger_profil "${PROFIL:-defaut}"
      ;;
      -l | --list)
      lister_profils
      ;;
      # Aide contextuelle
      -h | --help)
        aide
	;;
  esac
  shift
done


#####
## FIN
###

exit 0
# vim: ts=2 sw=2 et nu syn=bash
