#!/usr/bin/env bash
#
# genese: Outil pour générer des instances d'un à plusieurs projets via
#   Docker Compose en utilisant des profils pour savoir quels services
#   utiliser.
#

PROGRAMME=`basename $0 .sh`

#####
## VARIABLES
###

# Dépôt d'origine à télécharger
SOURCE="git@github.com:blankoworld/genese.git"

# Message d'utilisation du programme
read -d '' UTILISATION << EOF
Utilisation : ${PROGRAMME} [options]

OPTIONS
  -l, --list                Liste des profils disponibles
  -h, --help                Affichage de l'aide contextuelle
  -p, --profil <profil>     Utilisation du profil

EXEMPLE

    ${PROGRAMME} -h

EOF

# Profil par défaut pour créer des instances
PROFIL="defaut"

#####
## FONCTIONS
###

# Affiche l'aide contextuelle
aide() {
 echo -e "${UTILISATION}" 1>&2
}

# Liste des profils disponibles comme base pour les instances
lister_profils() {
  detection=false

  for profil in `ls ./profils`; do
    # Exclusion du profil commun
    if [[ "${profil}" != "commun" ]]; then
      echo -e "${profil}"
      detection=true
    fi
  done

  if ! ${detection}; then
    echo -e "Aucun profil trouvé."
  fi
}


# Découvre les services associés dans le fichier fourni
# Fonction récursive
# 1: Nom du profil situé dans le dossier ./profils
decouverte_services() {
  fichier="./profils/${1}"

  # Interruption si profil non trouvé.
  if [[ ! -f "./profils/${1}" ]]; then
    echo -e "Profil ${1} non trouvé !" && exit 1
  fi

  # Chargement des données fournies dans le fichier
  source "${fichier}"

  # Enregistrement des services fournis si la variable existe
  if [[ -n "${SERVICES}" ]]; then
    # chargement du tableau
    les_services="${SERVICES[@]}"

    # Comme nous sommes dans une récursive, on interrompt le processus en
    # supprimant la variable SERVICES
    unset SERVICES

    # Enregistrement
    for service in "${les_services[@]}"; do
      LISTE_SERVICES+=( "${service}" )
    done

  fi

  # Les fichiers peuvent avoir un parent
  if [[ -n "${PARENT}" ]]; then
    # chargement du parent
    profil_parent="${PARENT}"
    unset PARENT

    # récupération des services du parent
    decouverte_services "${profil_parent}"
  fi
}

# Listing des services trouvés
lister_services() {
  for service in ${LISTE_SERVICES[@]}; do
    echo "Service : ${service}"
  done
}

# Traite le chargement d'un profil
# 1: Nom du profil situé dans le dossier ./profils
charger_profil() {
  # Découverte de l'ensemble des services associés au fichier fourni
  decouverte_services "${PROFIL}"

  # Listing des services trouvés
  lister_services  
}

#####
## ARGUMENTS
###

[ "$#" -lt 1 ] && aide && exit 1

#####
## TESTS
###

#####
## DÉBUT
###

# Parcours des options
while [[ "$#" -gt 0 ]]
do
  case "$1" in
      -p | --profil)
      PROFIL="${2}"
      charger_profil "${PROFIL:-defaut}"
      ;;
      -l | --list)
      lister_profils
      ;;
      # Aide contextuelle
      -h | --help)
        aide
	;;
  esac
  shift
done

#####
## FIN
###

exit 0
# vim: ts=2 sw=2 et nu syn=bash
