style: gitlab
template: CHANGELOG.tpl.md
info:
  title: Genese CHANGELOG
  repository_url: https://github.com/blankoworld/genese
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
    sort_by: Scope
    title_maps:
      feat: Features
      fix: Bug fix
      refactor: Code refactoring
      doc: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
