db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: test
  volumes:
    - ${INSTALL_DIR}/bdd:/docker-entrypoint-initdb.d
